<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../VeraciInfra/VeraciInfra.csproj" />
    <ProjectReference Include="../VeraciLib/VeraciLib.csproj" />
  </ItemGroup>

</Project>
